name: Create active_threads.json and Auto Deploy
env:
  REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v3.0.2
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install
      - name: Create active_threads.json
        run: |
          npx tsx src/createActiveThreads.ts
      - name: Deploy
        run: |
          git config --global user.name "Clarence Chan"
          git config --global user.email "clarencechaan@icloud.com"
          git remote set-url origin https://${{ secrets.REDDILIVE_GH_TOKEN }}@github.com/clarencechaan/reddilive.git
          npm run deploy
