name: Create active_threads.json and Auto Deploy

on:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v3.0.2
        uses: actions/checkout@v4
        with:
          ref: fetch-active
      - name: Install dependencies
        run: |
          npm install
      - name: Create active_threads.json
        run: |
          npx tsx createActiveThreads.ts
      - name: Deploy
        run: |
          git config --global user.name "Clarence Chan"
          git config --global user.email "clarencechaan@icloud.com"
          npm run deploy
